### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by xxllp** [Huntersxsx/FastFoodOrder_demo1#1]
我要点餐
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/mlp/python/anaconda3/envs/py36/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/mlp/python/anaconda3/envs/py36/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/mlp/python/anaconda3/envs/py36/lib/python3.6/site-packages/rasa_core/channels/console.py", line 92, in record_messages
    text = get_cmd_input()
  File "/home/mlp/python/anaconda3/envs/py36/lib/python3.6/site-packages/rasa_core/channels/console.py", line 37, in get_cmd_input
    return input().strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe5 in position 6: invalid continuation byte

**Comment by xxllp** [comment]
现在可以了，但是回复的内容看起来很混乱。。。
